### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sardinecat13** [FrogTheFrog/frl-toggle#3]
Hello sorry I'm not sure what I'm doing wrong but this isnt working for me. Here are my commands 

DO:
C:\Sunshine\frltoggle.exe 60

UNDO:
C:\Sunshine\frltoggle.exe 0

my gsync toggle commands which are formatted the same way work but this doesnt. Am i doing something wrong?

**Comment by FrogTheFrog** [comment]
What's not working? Does the command fail with an error or what?

**Comment by sardinecat13** [comment]
It doesn’t give any errors after I run it but when I check the hz on my windows display settings the refresh rate still says 120 and the lg options pop up also says fps is 120.

**Comment by FrogTheFrog** [comment]
Please check in the nvidia control panel if the frame rate limiter is set to 60

**Comment by sardinecat13** [comment]
Whoops it does show it there! Sorry about that and thank you!
