### ISSUE TITLE
Adding a V-Sync toggle feature

### ISSUE THREAD

**Issue by gdiazbanuelos** [FrogTheFrog/frl-toggle#4]
Similar to the FPS limiter, is there anyway of adding the ability to change the Nvidia Control Panel Global settings for Vsync? When streaming over Moonlight I think having Vsync on affects the stream similarly to having the FPS limiter on.

Screenshot to show setting
![vsync](https://github.com/FrogTheFrog/frl-toggle/assets/39248490/84f05b6c-13a5-4b71-8c19-4b499e8baa10)

**Comment by FrogTheFrog** [comment]
There's a fork already
https://github.com/xanderfrangos/vsync-toggle

**Comment by gdiazbanuelos** [comment]
Thank you!
